### ISSUE TITLE
Marriage of services and ircd

### ISSUE THREAD

**Issue by Heartmender** [atheme-legacy/tethys#1]
Closer integration of Atheme to Tethys
- Entity id in user struct
- groups in groupserv for list-like modes

Discuss more options

**Comment by aji** [comment]
Integration should be with services in general, rather than targeted exclusively at Atheme. If you make a competing ircd that works best with only one services package, you lose all the users who don't want to use that services setup.

Also, any such integration should be very well-documented so that other services software teams can quickly write their own implementations.
